name: Test

on: [ pull_request ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError -XX:MetaspaceSize=1g"

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, macos-15, macos-15-intel, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Check API Compatibility
        if: matrix.os == 'macos-15'
        run: >
          ./gradlew apiCheck --stacktrace

      - name: Run macOS [x86_64] Tests
        if: matrix.os == 'macos-15-intel'
        run: >
          ./gradlew check --stacktrace
          -PKMP_TARGETS="JVM,JS,IOS_ARM64,IOS_X64,IOS_SIMULATOR_ARM64,TVOS_ARM64,TVOS_X64,TVOS_SIMULATOR_ARM64,WATCHOS_ARM32,WATCHOS_ARM64,WATCHOS_DEVICE_ARM64,WATCHOS_X64,WATCHOS_SIMULATOR_ARM64,WASM_JS,WASM_WASI"

      - name: Run macOS [aarch64] Tests
        if: matrix.os == 'macos-latest'
        run: >
          ./gradlew check --stacktrace
          -PKMP_TARGETS="JVM,JS,MACOS_ARM64,MACOS_X64,WASM_JS,WASM_WASI"

      - name: Run Linux Tests
        if: matrix.os == 'ubuntu-latest'
        run: >
          ./gradlew check --stacktrace
          -PKMP_TARGETS="JVM,JS,ANDROID,ANDROID_ARM32,ANDROID_ARM64,ANDROID_X64,ANDROID_X86,LINUX_ARM64,LINUX_X64,WASM_JS,WASM_WASI"

      - name: Run Windows Tests
        if: matrix.os == 'windows-latest'
        run: >
          ./gradlew check --stacktrace
          -PKMP_TARGETS="JVM,JS,MINGW_X64,WASM_JS,WASM_WASI"

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report-${{ matrix.os }}
          path: '**/build/reports/tests/**'
          retention-days: 1

  android-check:
    strategy:
      fail-fast: false
      matrix:
        include:
          - api-level: 15
            arch: x86
          - api-level: 19
            arch: x86
          - api-level: 21
            arch: x86
          - api-level: 23
            arch: x86_64
          - api-level: 24
            arch: x86
          - api-level: 30
            arch: x86_64
          - api-level: 35
            arch: x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Remove unnecessary tools
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          android: false
          tool-cache: true
          dotnet: true
          haskell: true
          swap-storage: true
          docker-images: false
          large-packages: false

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Run Android Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          emulator-boot-timeout: 300 # 5 minutes
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          script: ./gradlew connectedCheck -PKMP_TARGETS="ANDROID_ARM32,ANDROID_ARM64,ANDROID_X64,ANDROID_X86,ANDROID,JVM"

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report-android-${{ matrix.api-level }}-${{ matrix.arch }}
          path: |
            **/build/reports/androidTests/**
            **/build/outputs/androidTest-results/connected/debug/*/logcat-*.txt
          retention-days: 1
